#ifndef NET_CFG_H
#define NET_CFG_H

#define DBG_MBLOCK DBG_LEVEL_INFO
#define DBG_FIXQ DBG_LEVEL_INFO
#define DBG_EXMSG DBG_LEVEL_INFO

#define EXMSG_CNT 10
#define EXMSG_LOCKER NLOCKER_THREAD
#endif